<?php

namespace Aicl\Database\Seeders;

use Aicl\Enums\FailureCategory;
use Aicl\Enums\FailureSeverity;
use Aicl\Models\RlmFailure;
use Aicl\States\RlmFailure\Confirmed;
use App\Models\User;
use Illuminate\Database\Seeder;

class BaseFailureSeeder extends Seeder
{
    public function run(): void
    {
        $ownerId = User::first()?->id ?? 1;

        foreach ($this->baseFailures() as $failure) {
            RlmFailure::query()->updateOrCreate(
                ['failure_code' => $failure['failure_code']],
                $failure + [
                    'owner_id' => $ownerId,
                    'status' => Confirmed::getMorphClass(),
                    'is_active' => true,
                    'promoted_to_base' => true,
                    'promoted_at' => now(),
                    'aicl_version' => '1.1.0',
                ]
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function baseFailures(): array
    {
        return [
            [
                'failure_code' => 'BF-001',
                'category' => FailureCategory::Scaffolding,
                'severity' => FailureSeverity::High,
                'title' => 'HasStandardScopes::searchableColumns() defaults to [name, title]',
                'description' => 'Models without a title column get QueryException: Unknown column on search scope.',
                'attempt' => 'Scaffolded entity with default searchableColumns() returning [name, title].',
                'feedback' => 'QueryException: Unknown column "title" in LIKE query on search scope.',
                'root_cause' => 'searchableColumns() returns [name, title] by default. Models that lack a title column fail when the search scope builds a LIKE query against a non-existent column.',
                'fix' => 'Override searchableColumns() to return only columns that exist on the model table.',
                'preventive_rule' => 'When using HasStandardScopes, ALWAYS override searchableColumns() to list only columns that exist on the entity\'s table.',
                'validator_layer' => 'L1',
                'validator_id' => 'P-012',
                'phase' => 'phase-4',
                'scaffolding_fixed' => true,
            ],
            [
                'failure_code' => 'BF-002',
                'category' => FailureCategory::Process,
                'severity' => FailureSeverity::Critical,
                'title' => 'Entity registered before validation — pipeline order bypassed',
                'description' => 'Agent wired up entity (policy binding, observer, API routes, Filament resource discovery) WITHOUT running validation or tests first. Bypassed the validate→register pipeline order.',
                'attempt' => 'Architect agent invoked independently to generate entity code.',
                'feedback' => 'Entity was wired up in AppServiceProvider before validation or tests passed.',
                'root_cause' => 'No pipeline enforcement existed. The Architect agent was invoked independently and went straight to registration because it saw unregistered code.',
                'fix' => 'Implemented phase gate checks: Phase 5 (Register) requires Phase 4 (Validate) to pass first.',
                'preventive_rule' => 'Entity registration (policy binding, observer binding, API routes, Filament resource discovery) MUST happen in a separate phase AFTER validation passes. The pipeline enforces this via phase gate checks.',
                'phase' => 'phase-5',
                'scaffolding_fixed' => false,
            ],
            [
                'failure_code' => 'BF-003',
                'category' => FailureCategory::Scaffolding,
                'severity' => FailureSeverity::High,
                'title' => 'List page missing CreateAction; Table missing Export/record/bulk actions',
                'description' => 'List page missing CreateAction in header; Table missing ExportAction in headerActions, ViewAction/EditAction in recordActions, and ExportBulkAction/DeleteBulkAction in toolbarActions. Entity passed RLM validation and all tests but failed user acceptance testing.',
                'attempt' => 'Scaffolded entity with MakeEntityCommand, relying on default ListRecords page.',
                'feedback' => 'User acceptance testing revealed missing CreateAction, ExportAction, ViewAction, EditAction, and bulk actions.',
                'root_cause' => 'MakeEntityCommand scaffolding generated a bare ListRecords page without getHeaderActions() with CreateAction, and a table without headerActions, recordActions, or toolbarActions.',
                'fix' => 'Updated scaffolder to include all standard actions in ListRecords page and table definition.',
                'preventive_rule' => 'Scaffolding MUST include: (1) CreateAction on List page, (2) ExportAction in table headerActions, (3) ViewAction + EditAction in recordActions, (4) ExportBulkAction + DeleteBulkAction in toolbarActions BulkActionGroup.',
                'validator_layer' => 'L1',
                'phase' => 'phase-3',
                'scaffolding_fixed' => true,
            ],
            [
                'failure_code' => 'BF-004',
                'category' => FailureCategory::Process,
                'severity' => FailureSeverity::Critical,
                'title' => 'Context continuation caused agent to abandon pipeline',
                'description' => 'After context continuation (token limit truncation), agent abandoned structured pipeline — skipped phase gates, did not update pipeline documents, did not follow phase-gate discipline. Broad human directive compounded the issue.',
                'attempt' => 'Multi-entity generation in a single conversation session.',
                'feedback' => 'After token limit truncation, agent lost pipeline state and skipped phase gates.',
                'root_cause' => 'No instruction existed for detecting and recovering from context truncation. Human gave broad directive without requesting explicit phase-gate checkpoints.',
                'fix' => 'Added context continuity check to all agent prompts: re-read pipeline documents after any suspected continuation.',
                'preventive_rule' => 'After ANY context continuation, agents MUST re-read all active pipeline documents before resuming work. Pipeline document is the source of truth, not conversational memory. Multi-entity projects process ONE entity at a time with human checkpoints.',
                'scaffolding_fixed' => false,
            ],
            [
                'failure_code' => 'BF-005',
                'category' => FailureCategory::Filament,
                'severity' => FailureSeverity::High,
                'title' => 'searchableColumns() defaults break Filament search',
                'description' => 'HasStandardScopes::searchableColumns() returns [name, title] by default. Models without title column get 500 errors on search scope in Filament admin.',
                'attempt' => 'Scaffolded entity without overriding searchableColumns().',
                'feedback' => '500 error on Filament global search when model lacks title column.',
                'root_cause' => 'Same root cause as BF-001, but manifests in Filament global search context specifically.',
                'fix' => 'Override searchableColumns() to return only columns present on the model.',
                'preventive_rule' => 'Always override searchableColumns() to list only columns that exist on the entity\'s table.',
                'validator_layer' => 'L1',
                'validator_id' => 'P-012',
                'phase' => 'phase-4',
                'scaffolding_fixed' => true,
            ],
            [
                'failure_code' => 'BF-006',
                'category' => FailureCategory::Filament,
                'severity' => FailureSeverity::Medium,
                'title' => 'Filament v4 form field HTML id uses form. prefix, not data.',
                'description' => 'Filament v4 form field HTML id uses form. prefix (e.g., id="form.email"), NOT data. wire:model uses data.email but the HTML id is form.email.',
                'attempt' => 'Wrote Dusk test targeting #data.email selector.',
                'feedback' => 'Dusk test failed: element not found with selector #data.email.',
                'root_cause' => 'Filament v4 changed the HTML id generation to use form. prefix instead of data. prefix.',
                'fix' => 'Changed Dusk selectors to use form.{field} for #id selectors.',
                'preventive_rule' => 'In Dusk tests, use form.{field} for #id selectors and data.{field} for wire:model selectors.',
                'phase' => 'phase-4',
                'scaffolding_fixed' => false,
            ],
            [
                'failure_code' => 'BF-007',
                'category' => FailureCategory::Auth,
                'severity' => FailureSeverity::High,
                'title' => 'Spatie Permission + API guard: permissions not found across guards',
                'description' => 'actingAs($user, \'api\') changes the default guard to api. Permissions seeded only on web guard won\'t be found.',
                'attempt' => 'Ran API tests with actingAs($user, \'api\') after seeding permissions on web guard only.',
                'feedback' => 'UnauthorizedException: User does not have the right permissions (api guard).',
                'root_cause' => 'Spatie Permission scopes permission checks to the current guard. When actingAs changes to api guard, permissions seeded only on web guard are invisible.',
                'fix' => 'Seed permissions and roles on both web and api guards in test seeders.',
                'preventive_rule' => 'Seed permissions AND roles on BOTH web and api guards. Assign roles on both guards for API tests.',
                'validator_layer' => 'OTHER',
                'phase' => 'phase-4',
                'scaffolding_fixed' => false,
            ],
            [
                'failure_code' => 'BF-008',
                'category' => FailureCategory::Laravel,
                'severity' => FailureSeverity::Medium,
                'title' => 'EntityDeleted event must not use SerializesModels',
                'description' => 'Entity events with ShouldBroadcast: EntityDeleted must NOT use SerializesModels trait because the model may already be deleted when the event is processed.',
                'attempt' => 'Generated EntityDeleted event class with SerializesModels trait.',
                'feedback' => 'ModelNotFoundException when broadcasting delete event: model not found during serialization.',
                'root_cause' => 'SerializesModels attempts to re-fetch the model from the database during serialization. If the model is soft-deleted or hard-deleted, this fails.',
                'fix' => 'Removed SerializesModels from EntityDeleted event; pass scalar data instead of model instance.',
                'preventive_rule' => 'Never use SerializesModels in delete event classes.',
                'validator_layer' => 'L1',
                'phase' => 'phase-3',
                'scaffolding_fixed' => false,
            ],
            [
                'failure_code' => 'BF-009',
                'category' => FailureCategory::Testing,
                'severity' => FailureSeverity::Medium,
                'title' => 'Livewire lifecycle hooks cannot be called directly via ->call()',
                'description' => 'Livewire lifecycle hooks (updatedQuery, updatedEntityType) cannot be called directly via ->call() in Livewire tests.',
                'attempt' => 'Used Livewire::test(Component::class)->call(\'updatedQuery\', \'test\').',
                'feedback' => 'Lifecycle hook was not triggered; property state was not updated.',
                'root_cause' => 'Livewire lifecycle hooks are triggered by property changes, not direct method calls. Using ->call() on a lifecycle hook bypasses the property change detection.',
                'fix' => 'Replaced ->call(\'updatedQuery\') with ->set(\'query\', \'test\').',
                'preventive_rule' => 'Set the property via ->set() which triggers the hook automatically.',
                'phase' => 'phase-4',
                'scaffolding_fixed' => false,
            ],
            [
                'failure_code' => 'BF-010',
                'category' => FailureCategory::Testing,
                'severity' => FailureSeverity::Medium,
                'title' => 'Routes registered in test setUp() missing from named route lookup',
                'description' => 'Routes registered in test setUp() are in the route collection but NOT in the named route lookup.',
                'attempt' => 'Registered API routes in test setUp() method and used route() helper to generate URLs.',
                'feedback' => 'InvalidArgumentException: Route [entities.index] not defined.',
                'root_cause' => 'Laravel caches the named route lookup. Routes added after initial compilation are in the collection but not discoverable by name.',
                'fix' => 'Added app(\'router\')->getRoutes()->refreshNameLookups() after registering routes in tests.',
                'preventive_rule' => 'Call app(\'router\')->getRoutes()->refreshNameLookups() after registering routes in tests.',
                'phase' => 'phase-4',
                'scaffolding_fixed' => false,
            ],
            [
                'failure_code' => 'BF-011',
                'category' => FailureCategory::Filament,
                'severity' => FailureSeverity::Medium,
                'title' => 'DoughnutChartWidget class is deprecated in Filament v4',
                'description' => 'DoughnutChartWidget class is deprecated in Filament v4. Using it causes deprecation warnings.',
                'attempt' => 'Generated widget extending DoughnutChartWidget.',
                'feedback' => 'PHP deprecation warning: DoughnutChartWidget is deprecated, use ChartWidget.',
                'root_cause' => 'Filament v4 consolidated chart widgets into a single ChartWidget class with configurable chart types.',
                'fix' => 'Changed widget to extend ChartWidget and added getType() returning \'doughnut\'.',
                'preventive_rule' => 'Use ChartWidget with getType() returning \'doughnut\'.',
                'validator_layer' => 'L1',
                'phase' => 'phase-3',
                'scaffolding_fixed' => true,
            ],
            [
                'failure_code' => 'BF-012',
                'category' => FailureCategory::Filament,
                'severity' => FailureSeverity::Critical,
                'title' => 'Section/Grid namespace is Filament\Schemas\Components, not Forms\Components',
                'description' => 'Section is in Filament\Schemas\Components\Section, NOT Filament\Forms\Components\Section. Same for Grid.',
                'attempt' => 'Used Filament\Forms\Components\Section in form schema.',
                'feedback' => 'L1 pattern P-001 failed: wrong namespace for Section component.',
                'root_cause' => 'Filament v4 moved layout components to a separate Schemas namespace while keeping form input components in Forms.',
                'fix' => 'Changed use statement to Filament\Schemas\Components\Section.',
                'preventive_rule' => 'Form components (TextInput, Select, Toggle) are in Filament\Forms\Components. Layout components (Section, Grid) are in Filament\Schemas\Components.',
                'validator_layer' => 'L1',
                'validator_id' => 'P-001',
                'phase' => 'phase-4',
                'scaffolding_fixed' => false,
            ],
            [
                'failure_code' => 'BF-013',
                'category' => FailureCategory::Tailwind,
                'severity' => FailureSeverity::High,
                'title' => 'Tailwind v4 does not support dynamic class interpolation',
                'description' => 'Tailwind v4 does not support dynamic class interpolation (bg-{{ $color }}-500). Classes must be complete strings at compile time.',
                'attempt' => 'Used dynamic Blade interpolation in Tailwind class: bg-{{ $color }}-500.',
                'feedback' => 'Tailwind classes not applied: bg-blue-500 not found in compiled CSS.',
                'root_cause' => 'Tailwind v4 uses a JIT compiler that scans source files for complete class names. Dynamic interpolation produces class names that don\'t exist at compile time.',
                'fix' => 'Replaced interpolation with explicit match expression returning complete class strings.',
                'preventive_rule' => 'Use explicit match expressions that return complete class strings. Never interpolate Tailwind class fragments.',
                'phase' => 'phase-3',
                'scaffolding_fixed' => false,
            ],
            [
                'failure_code' => 'BF-014',
                'category' => FailureCategory::Testing,
                'severity' => FailureSeverity::Medium,
                'title' => 'phpunit.xml needs BROADCAST_CONNECTION=log for tests',
                'description' => 'phpunit.xml needs BROADCAST_CONNECTION=log to prevent broadcast driver failures during tests. Without it, tests that trigger broadcastable events will fail.',
                'attempt' => 'Ran tests with default broadcast driver (pusher/reverb).',
                'feedback' => 'BroadcastException: unable to connect to broadcast server during tests.',
                'root_cause' => 'Default broadcast driver may not be available in test environment. Broadcastable events dispatched during tests fail if the driver cannot connect.',
                'fix' => 'Added <env name="BROADCAST_CONNECTION" value="log"/> to phpunit.xml.',
                'preventive_rule' => 'Always set BROADCAST_CONNECTION=log in test environment config (phpunit.xml or .env.testing).',
                'phase' => 'phase-4',
                'scaffolding_fixed' => true,
            ],
            [
                'failure_code' => 'BF-015',
                'category' => FailureCategory::Configuration,
                'severity' => FailureSeverity::High,
                'title' => 'Never modify published migrations after release',
                'description' => 'Framework development consolidated multiple migrations into single files. This works for fresh installs but would break existing databases that already ran the original split migrations.',
                'attempt' => 'Consolidated multiple migration files into single files during framework development.',
                'feedback' => 'Existing databases that ran original migrations would not re-run consolidated versions.',
                'root_cause' => 'Merging migrations assumes no database has ever run the original versions. Existing databases track migration names and would not re-run consolidated versions.',
                'fix' => 'Reverted consolidation; created new additive migration for schema changes.',
                'preventive_rule' => 'NEVER modify a published migration after it has been tagged in a release. Always create a new migration for schema changes. Consolidation is only safe before first release or for fresh skeleton builds.',
                'scaffolding_fixed' => false,
            ],
        ];
    }
}
