<?php

declare(strict_types=1);

namespace Aicl\Filament\Resources\AiConversations\Schemas;

use Aicl\Models\AiAgent;
use Aicl\States\AiConversation\Active;
use Aicl\States\AiConversation\Archived;
use Aicl\States\AiConversation\Summarized;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

/**
 * @codeCoverageIgnore Filament Livewire rendering
 */
class AiConversationForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Conversation')
                    ->columns(2)
                    ->columnSpanFull()
                    ->schema([
                        TextInput::make('title')
                            ->maxLength(255)
                            ->placeholder('Auto-generated if left blank'),
                        Select::make('user_id')
                            ->label('User')
                            ->relationship('user', 'name')
                            ->searchable()
                            ->preload()
                            ->required(),
                        Select::make('ai_agent_id')
                            ->label('Agent')
                            ->options(fn (): array => AiAgent::query()->pluck('name', 'id')->toArray())
                            ->searchable()
                            ->required(),
                        Select::make('state')
                            ->options([
                                Active::class => 'Active',
                                Summarized::class => 'Summarized',
                                Archived::class => 'Archived',
                            ])
                            ->hidden(fn (string $operation): bool => $operation === 'create'),
                        Toggle::make('is_pinned')
                            ->label('Pinned')
                            ->inline(),
                        TextInput::make('context_page')
                            ->maxLength(500)
                            ->placeholder('/admin/dashboard'),
                    ]),

                Section::make('Usage')
                    ->columns(2)
                    ->columnSpanFull()
                    ->schema([
                        TextInput::make('message_count')
                            ->numeric()
                            ->default(0)
                            ->disabled(),
                        TextInput::make('token_count')
                            ->numeric()
                            ->default(0)
                            ->disabled(),
                    ]),

                Section::make('Compaction')
                    ->columnSpanFull()
                    ->schema([
                        Textarea::make('summary')
                            ->rows(6)
                            ->columnSpanFull()
                            ->helperText('Generated by the compaction service when messages exceed the threshold'),
                    ]),
            ]);
    }
}
