<?php

declare(strict_types=1);

namespace Aicl\Console\Support;

/**
 * Shared validation helpers for spec file parsers and validators.
 *
 * Provides common naming convention checks, type validation,
 * and format assertions used across SpecFileParser, ValidateSpecCommand,
 * and future spec validators (ToolSpecParser, PermissionSpecParser).
 */
trait SpecValidation
{
    /**
     * Check if a string is PascalCase (e.g., InvoiceLineItem).
     */
    protected function isPascalCase(string $value): bool
    {
        return preg_match('/^[A-Z][a-zA-Z0-9]+$/', $value) === 1;
    }

    /**
     * Check if a string is snake_case (e.g., invoice_line_item).
     */
    protected function isSnakeCase(string $value): bool
    {
        return preg_match('/^[a-z][a-z0-9_]*$/', $value) === 1;
    }

    /**
     * Check if a string is camelCase (e.g., lineItems).
     */
    protected function isCamelCase(string $value): bool
    {
        return preg_match('/^[a-z][a-zA-Z0-9]*$/', $value) === 1;
    }

    /**
     * Check if a field type is a supported column type.
     */
    protected function isValidColumnType(string $type): bool
    {
        return in_array($type, [
            'string', 'text', 'integer', 'float', 'boolean',
            'date', 'datetime', 'enum', 'json', 'foreignId',
        ], true);
    }

    /**
     * Check if a column name is reserved (auto-generated by framework).
     */
    protected function isReservedColumn(string $name): bool
    {
        return in_array($name, ['id', 'created_at', 'updated_at', 'deleted_at'], true);
    }

    /**
     * Check if a column is auto-generated by base traits.
     */
    protected function isAutoColumn(string $name): bool
    {
        return in_array($name, ['is_active', 'owner_id'], true);
    }

    /**
     * Check if a trait name is a recognized AICL trait.
     */
    protected function isKnownTrait(string $trait): bool
    {
        return in_array($trait, [
            'HasEntityEvents',
            'HasAuditTrail',
            'HasStandardScopes',
            'HasTagging',
            'HasSearchableFields',
            'HasAiContext',
        ], true);
    }

    /**
     * Check if an option key is a recognized AICL entity option.
     */
    protected function isKnownOption(string $key): bool
    {
        return in_array($key, [
            'widgets', 'notifications', 'pdf', 'ai-context',
            'filament', 'api', 'base',
        ], true);
    }

    /**
     * Check if a relationship type is supported.
     */
    protected function isValidRelationshipType(string $type): bool
    {
        return in_array($type, [
            'hasMany', 'hasOne', 'belongsToMany', 'morphMany',
        ], true);
    }
}
